version: '3'
services:
  tor:
    container_name: hidden-service
    image: strm/tor
    restart: always
    depends_on:
      - nginx
    environment:
      LISTEN_PORT: "80"
      REDIRECT: "nginx:80"
      PRIVATE_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        MIICXgIBAAKBgQ3aFa5DIf0id09fd09ff9Y79Q2L5tvMbwMiGVYwYaOIV5wFZ8Hr
        bYL+sY5+A2Dakw1sD+Otgj2iIvCEDytonjQpeUikA2A3sl02pET1S3C0TMhL5ybx
        msi2TWyv6w1JGHk2CYCqPKe8fylg0yTF/rpUSPUINYrs15gn18m6rT602wIEARQs
        rwKBgDk+r2UDRunte9a8f7d89f7a89sd7f98af9das87dqL7xSMsnWgvrlVBlX6m
        icN3DoFciUMWTDlAWIcqiJw9TZbiWnL460XqF7/OT9GmjVJa2bC+1x9SOpKgcg0l
        uVzR24r0fT77q7Hdh1+KPhR+YbkI01oD1PytULxjNVmko7xfAkEA4B1Ke8Zsd0Nd
        DOMKDGK6YSzZnBf6K4ym9511ogUhC1oYMc63H9lk31wn/o9XRpjT9Si4XsxNuKR6
        uUjizsVG+9a8usdf9au8sdf98uasdf8dsfu98asudfufN+s1eXL+ajnx8FlVbhXw
        EgxHCsJT1eTySV3wNcVM8SAH3fHNrc5UK3MCQGko0R5Mhbztij+7+s0bbGP+x7Fb
        7Dlhiee58KcYg3nejgHMzvLS5k1YYslzMwGMjt1ZNluF655m72cJ8Ra2KGcCQQCW
        NtQUbNxupRSopW1/spVjDH7Euyms8l/RiQtz9KyKLuGGzIYw4IbzqWU3YFzNKNWZ
        JTjg0ba9d8faus9d8fua98sdufausd9f8ud98p89uAUFZAOgMMAYXOrP90XJLO1/
        XW8c8VZmX29LqD9fjiJKPA2VHxgCRI2tdUgpqnoxgJjxOA==
        -----END RSA PRIVATE KEY-----
  blockchain:
    container_name: blockchain-tor
    image: blockchain-tor
    restart: on-failure
    build:
      context: blockchain
    ports:
      - "5001:5000"
  nginx:
    container_name: nginx-tor
    image: nginx
    restart: always
    build:
      context: web
    ports:
      - "5000:80"
    depends_on:
      - blockchain
